### ISSUE TITLE
有時候整棟物件的樓層會顯示為 99 樓...

### ISSUE THREAD

**Issue by ddio** [g0v/tw-rental-house-data#11]
1. 資料庫裡有些物件的樓層是 99 樓，看起來都是整棟出租的會有這個問題

## 事發原因
1. 591 List API 回傳的資料中，如果是整層的，會把樓層標為 `99`  XDDD
2. 後來發現頂加則會被標成 `100` ....
2. 在某些情況下，List API 的結果會比 Detail API 還要晚進 Scrapy pipeline ，或是到 Detail API 時已經抓不到此物件 ，導致 99 樓出現...
3. 另外，這會導致 dist_to_highest_floor 對不起來

## 治本
1. List Spider 手動偵測 99 樓，硬改回 0 .....
2. List Spider 手動偵測 100 樓，硬改回 total_floor+1 .....

## 治標
1. `update house set floor = 0, dist_to_highest_floor = total_floor where floor = 99 and floor > total_floor;`  ...
2. `update house set floor = (total_floor+1), dist_to_highest_floor = -1 where floor = 100 and is_rooftop = true;`

**Comment by suensummit** [comment]
（未看先問）這樣的話`頂加`是不是需要另外加欄位標注啊？

**Comment by ddio** [comment]
有的～目前開放的資料集裡有[自報頂加？](https://rentalhouse.g0v.ddio.io/about-data-set/0.1#%E7%89%A9%E4%BB%B6%E7%A1%AC%E9%AB%94%E8%B3%87%E8%A8%8A) 可以拿來判斷～

591 的話網頁上會寫「頂樓」或是 100 ，看你從哪裡抓 XDDD
