### ISSUE TITLE
資料相關疑問

### ISSUE THREAD

**Issue by sushi3085** [g0v/tw-rental-house-data#165]
您好，我是蘇煒翔，是目前參與執行「包租隔套產業與捷運系統縉紳化」計畫的研究助理，
由於目前會使用到打包回家玩的資料，想請問2022年消除重複住宅的資料，是否為包含2022年之前所有的物件，而非只有2022年當年自身消除重複物件的資料，謝謝！

**Comment by ddio** [comment]
「2022年消除重複住宅」僅包含 2022 中曾經出現過的物件呦～

**Comment by sushi3085** [comment]
了解！十分感謝！
