### ISSUE TITLE
[Doc] Improvement of UI's source code link

### ISSUE THREAD

**Issue by tan-i-ham** [g0v/tw-rental-house-data#172]
When I checking the issue https://github.com/g0v/tw-rental-house-data/issues/2, and try to read the source code of ui
and found the `README.md` can be improved.

https://github.com/g0v/tw-rental-house-data/blob/b8a61dc830699e5a6ef516025967404ccab01545/README.md?plain=1#L18

## AS-IS
```
3. `ui` - 開放台灣租屋資料網站
   - [原始碼](https://github.com/g0v/tw-rental-house-data/tree/master/twrh-dataset)
```

## TO-BE
```
3. `ui` - 開放台灣租屋資料網站
   - [原始碼](https://github.com/g0v/tw-rental-house-data/tree/master/ui)
```

**Comment by ddio** [comment]
@tan-i-ham , thanks for reporting this. Feel free to send PR!

**Comment by tan-i-ham** [comment]
@ddio Thank you for the comment.
I have sent the PR and link the issue number with the target PR.
